name: yum_health
description: Aplikasi Resep dengan Perhitungan Berat Badan Ideal untuk Rekomendasi Menu

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0-nullsafety.0
  google_fonts: ^2.1.0
  animate_do: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/pancake.png
    - images/avocado.png
    - images/sushi.jpg


